# Generated by Django 5.0.1 on 2024-01-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum', models.IntegerField()),
                ('waiting_cost', models.IntegerField()),
                ('bonus_percent', models.IntegerField()),
                ('baggage_cost', models.IntegerField()),
                ('type', models.CharField(max_length=40)),
                ('sum_per_km', models.IntegerField()),
            ],
        ),
    ]
