# Generated by Django 5.0.1 on 2024-01-29 09:45

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fullname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('car_type', models.CharField(max_length=30)),
                ('car_number', models.CharField(max_length=40)),
                ('sms_code', models.CharField(max_length=40)),
                ('confirmed', models.BooleanField(default=False)),
                ('balance', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=30)),
                ('has_baggage', models.BooleanField(default=False)),
                ('created_at', models.DateField()),
                ('photo', models.FileField(upload_to='')),
                ('birth_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.carcategory')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
