# Generated by Django 5.0.1 on 2024-01-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('Naxt', 'Naxt'), ('Karta', 'Karta')], max_length=40)),
                ('date', models.DateField()),
            ],
        ),
    ]
